version: "3"

services:
  airflow:
    build: ./airflow
    restart: unless-stopped
    environment:
      - AIRFLOW__CORE__FERNET_KEY=PeszOD9t6wKNdNONTGh-k4qsYbsGHQ8CSqTQZlqPCDk=
      - AIRFLOW_HOME=/opt/airflow
    ports:
      - 8000:8000
    volumes:
      - airflow:/opt/airflow/dags
    command: sleep infinity

  spark-master:
    build: ./spark
    restart: unless-stopped
    ports:
      - 8080:8080
    command: sh spark-master.sh

  spark-worker:
    build: ./spark
    restart: unless-stopped
    ports:
      - "8081-8085:8081"
    command: sh spark-worker.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  minio:
    image: "minio/minio:latest"
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "root12345"
    command: server /data --console-address ":9001"


  mariadb:
    image: mariadb:latest
    # image: mariadb/columnstore:latest
    ports:
      - 3306:3306
    environment:
      USE_S3_STORAGE: 0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive:
    build: ./hive
    restart: unless-stopped
    ports:
      - 9083:9083
  
  
  jupyter:
    build: ./jupyter
    restart: unless-stopped
    volumes:
      - jupyter:/home/jovyan
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  airflow:
  minio:
  jupyter:
